# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataAugmentation
                                 A QGIS plugin
 This plugin generate basic data augmentation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-07
        copyright            : (C) 2021 by Gabriel K. Alves, Sabrina G. Marques, Igor Kolesnikov, Rafael Marinho
        email                : gabriel.alves@inpe.br, rafael.andrade@inpe.br, sabrina.marques@inpe.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataAugmentation class from file DataAugmentation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DataAugmentation import DataAugmentation
    return DataAugmentation(iface)
