# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataAugmentation
                                 A QGIS plugin
 This plugin generate basic data augmentation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-07
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Gabriel K. Alves, Sabrina G. Marques, Igor Kolesnikov, Rafael Marinho
        email                : gabriel.alves@inpe.br, rafael.andrade@inpe.br, sabrina.marques@inpe.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .DataAugmentation_dialog import DataAugmentationDialog
import os.path


# My imports
import os
from qgis import processing

from qgis.gui import QgsMapToolPan
from qgis.core import QgsProject, Qgis, QgsRasterLayer, QgsCoordinateReferenceSystem, QgsCoordinateTransform
from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.QtWidgets import QTreeWidget, QTreeWidgetItem, QApplication, QWidget

# Graphic view
from PyQt5.QtCore import Qt
from PIL import Image, ImageQt
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QRectF
from PyQt5.QtWidgets import QGraphicsScene, QHBoxLayout, QGraphicsView

import sip
import cv2
import glob
import shutil

from osgeo import gdal, osr, ogr

import operator
import numpy as np
from random import randint
from skimage.transform import resize
from scipy.ndimage import gaussian_filter

class Methods_Augmentate:

    def __init__(self):
        pass

        # Rotação:
    
    def rotate(self, img, degrees):
        return (np.rot90(img, k=int(degrees / 90)))

    # Espelhamento:
    def flip(self, img, direction):
        if (direction == "vertical"):
            return (img[::-1, ::])
        elif (direction == "horizontal"):
            return (img[::, ::-1])
        elif (direction == "both"):
            return (img[::-1, ::-1])

    # Aparagem:
    def trim(self, img, top=0, bottom=0, left=0, right=0):
        return (img[top:-bottom, right:-left])

    # Recorte:
    def crop(self, img, right=0, top=0, left=100, bottom=100):
        return (img[top:bottom, right:left])

    # Gaussian blur:
    def blur(self, img, sigma=1):
        return(gaussian_filter(img, sigma=sigma))

    # Redimensionamento:
    def rescale(self, img, ratio):
        return (resize(img, (int(img.shape[1] * ratio), int(img.shape[0] * ratio))))

    # Binarização:
    def binary(self, img, threshold=120, inv=False, bw=True):
        if (inv == False):
            method = cv2.THRESH_BINARY
        else:
            method = cv2.THRESH_BINARY_INV

        if (bw == True):
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        return(cv2.threshold(img, threshold, 255, method)[1])

    # Truncagem:
    def trunc(self, img, threshold=120, max=255):
        return (cv2.threshold(img, threshold, max, cv2.THRESH_TRUNC)[1])

    # Extração e realce de bordas:
    def edgy(self, img, threshold=120, max=255, aperture=3, mask=True):

        if(img.dtype != "uint8"): img = img.astype('uint8')

        edges = cv2.Canny(img, threshold, max, aperture)

        if (mask == True):
            return (cv2.bitwise_and(img, img, mask=cv2.bitwise_not(edges)))

        return(edges)
    
    # Rotina de data augmentation:
    def augmentate(self, img, name, chunks=100, invert=3, rotations=3, blur_sigmas=5):
        
        res = dict()
        labelImg = dict()
        areas = []

        while (len(areas) != chunks):
            x = randint(0, img.shape[1] - chunks)
            y = randint(0, img.shape[0] - chunks)
            if ((x, y) not in areas):
                areas.append((x, y))

        count = 1


        for i, coords in enumerate(areas):
            nimg = self.crop(img, coords[0], coords[1], coords[0] + chunks, coords[1] + chunks)
            nm1 = (name+"_"+str(i)).upper()

            for idx, x in enumerate([nimg, self.flip(nimg, "vertical"), self.flip(nimg, "horizontal"), self.flip(nimg, "both")][:invert + 1]):
                nm1 += "_" + str(idx)
                res[nm1] = dict()

                for idx2, y in enumerate([0, 90, 180, 270][:rotations + 1]):
                    nm2 = ("_ROTATE_" + str(y)).upper()
                    _img = self.rotate(x, y)

                    if(np.count_nonzero(_img) == 0): continue

                    res[nm1][nm1 + nm2] = dict()
                    res[nm1][nm1 + nm2]['name'] = nm1 + nm2

                    labelImg[nm1 + nm2] = _img

                    count+=1

                    for idx3, s in enumerate(range(1, blur_sigmas + 1)):
                        nm3 = ("_BLUR_" + str(s)).upper()
                        _img = self.rotate(self.blur(x, sigma=s), y)

                        if(np.count_nonzero(_img) == 0): continue

                        res[nm1][nm1 + nm2 + nm3] = dict()
                        res[nm1][nm1 + nm2 + nm3]['name'] = nm1 + nm2 + nm3

                        labelImg[nm1 + nm2 + nm3] = _img
                        count+=1


        return res, labelImg, count

    def cloud(self, img):
        # Opening the primary image (used in background)
        img1 = Image.fromarray(img)
            
        # Opening the secondary image (overlay image)
        # folder 
        
        png_path = os.path.join(os.path.split(__file__)[0], 'cloud_template.png')
        img2 = Image.open(png_path)

        # resize the image
        size = img1.size
        img2 = img2.resize(size,Image.ANTIALIAS)

        img1 = np.asarray(img1)
        img2 = np.asarray(img2)

        cloud_mask = img2[:,:,0]

        res = np.where(cloud_mask == 0, img1, cloud_mask)

        return res

    def gdalDecreaseResolution(self, dataset, src, limiar=3, dst="/tmp/decrease.tif"):

        xres, yres = operator.itemgetter(1,5)(dataset.GetGeoTransform())  

        xres*=limiar
        yres*=limiar

        gdal.Warp(dst, src, xRes=xres, yRes=yres)

        res = gdal.Open(dst)
        res_b = res.GetRasterBand(1)
        res_arr = res_b.ReadAsArray()

        return res_arr

methods_augmentate = Methods_Augmentate()

class DataAugmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DataAugmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Data Augmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Variables

        # Selected Layer
        self.selectedName = None
        self.selectedNameVector = None
        self.selected = dict()

        self.type = dict()
        self.type['layer']  = 'Layer'
        self.type['vector'] = 'Vector'

        # treeview
        self.methodItem = dict()

        self.topAugmentateTree = None
        self.rotate            = None
        self.blur              = None
        self.reshape           = None
        self.color             = None
        self.remote_sensing    = None
        self.flip              = None

        # Shape formats
        self.sf = ['.shp', '.geojson']

        # All methods
        self.methods = dict()

        # Split vector
        self.vectorsPath = []
        self.vectorsBufferPath = []
        self.imagesArray = []

        self.child = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DataAugmentation', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/DataAugmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Data Augmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Data Augmentation'),
                action)
            self.iface.removeToolBarIcon(action)

    def selectLayerFile(self):
        selectedLayerPath, _ = QFileDialog.getOpenFileName(self.dlg, "Select input layer file", "", "*.tif")
        
        if(selectedLayerPath != ""):
            nameLayer = os.path.split(selectedLayerPath)[-1]
            nameLayer = nameLayer if os.path.splitext(nameLayer)[1] == "" else (os.path.splitext(nameLayer)[0]) # Remove extension

            self.dlg.layerCombo.addItem(nameLayer)
            self.dlg.layerCombo.setCurrentText(nameLayer)

            self.selectedName = nameLayer

            self.selected[nameLayer] = dict()
            self.selected[nameLayer]['path'] = selectedLayerPath
            self.selected[nameLayer]['type'] = self.type['layer']

    def selectVectorFile(self):
        selectedVectorPath, _ = QFileDialog.getOpenFileName(self.dlg, "Select input vector file", "", "*.shp;;*.geojson;;*.zip")

        if(selectedVectorPath != ""):

            nameVector   = os.path.split(selectedVectorPath)[-1]
            nameVector = nameVector if os.path.splitext(nameVector)[1] == "" else (os.path.splitext(nameVector)[0])

            self.dlg.vectorCombo.addItem(nameVector)
            self.dlg.vectorCombo.setCurrentText(nameVector)

            self.selectedNameVector = nameVector

            self.selected['name'] = nameVector
            self.selected['path'] = selectedVectorPath
            self.selected['type'] = self.type['vector']

    def readShape(self, src=None):
        if(src == None): src = self.selected[self.selectedNameVector]['path']

        shapefile = ogr.Open(src)
        layer = shapefile.GetLayer(0)

        return shapefile, layer

    def splitPoint(self, dst=None):

        if(dst == None): dst = "/tmp/tmp_point.shp"

        shapefileRef, layerRef = self.readShape()

        # set up the shapefile driver
        driver = ogr.GetDriverByName("ESRI Shapefile")

        # create the spatial reference
        srs = layerRef.GetSpatialRef()

        for idx, featureRef in enumerate(layerRef):

            # name output
            dst_name = dst.replace(".shp", "_" + str(idx) + ".shp")

            # geometry 
            geometry = featureRef.GetGeometryRef()

            # create the data source
            data_source = driver.CreateDataSource(dst_name)

            # create the layer
            layer = data_source.CreateLayer("point", srs, ogr.wkbPoint)

            # create the feature
            feature = ogr.Feature(layer.GetLayerDefn())

            feature.SetGeometry(geometry)
            layer.CreateFeature(feature)

            self.vectorsPath.append(dst_name)

        feature = None
        data_source = None

    def readLayer(self, src=None):

        dataset = dict()

        # if src not provided read path selected layer
        if(src == None): 
            self.dataset = gdal.Open(self.selected[self.selectedName]['path'])
        else:
            self.dataset = gdal.Open(src)

        # Get first band -- considering only one band tif as input
        self.band      = self.dataset.GetRasterBand(1)
        self.bandArr   = self.band.ReadAsArray()


        # Get properties to save later
        self.geoTransform = self.dataset.GetGeoTransform()
        self.projection = self.dataset.GetProjection()

        # Mount dataset
        dataset["dataset"]      = self.dataset
        dataset["bandArr"]      = self.bandArr
        dataset["geoTransform"] = self.geoTransform
        dataset["projection"]   = self.projection

        # Validation
        # if image too big return
        # if(self.bandArr.shape()[0] > 5000 and self.bandArr.shape()[0] > 5000):
        # if(True): return "ok" #"err"
        # else: return "ok"

        return dataset

    def saveLayer(self, dst, arr):

        # check dst name extension
        dst = dst if os.path.splitext(dst)[1] != "" else (dst+".tif")

        [rows, cols] = arr.shape

        driver = gdal.GetDriverByName("GTiff")
        outdata = driver.Create(dst, cols, rows, 1, gdal.GDT_UInt16)

        outdata.SetGeoTransform(self.geoTransform)
        outdata.SetProjection(self.projection) 
        outdata.GetRasterBand(1).WriteArray(arr)
        outdata.GetRasterBand(1).SetNoDataValue(10000)

        outdata.FlushCache()

        outdata = None

        return dst
    
    def getBufferPoint(self, src, dst=None, buffer=0.01):

        # https://docs.qgis.org/3.16/en/docs/user_manual/processing/console.html
        parameters = {'INPUT': '/data/lines.shp',
               'DISTANCE': 0.1,
               'SEGMENTS': 10,
               'DISSOLVE': True,
               'END_CAP_STYLE': 0,
               'JOIN_STYLE': 0,
               'MITER_LIMIT': 10,
               'OUTPUT': '/data/buffers.shp'}

        parameters['INPUT'] = src
        parameters['DISTANCE'] = buffer

        if(dst == None): parameters['OUTPUT'] = "/tmp/buffer.shp"
        else: parameters['OUTPUT'] = dst

        processing.run("native:buffer", parameters)

        return parameters['OUTPUT']

    def cropLayerByShape(self, src, shape, dst=None, dstNodata=0):

        if(dst == None):
            name = os.path.split(src)[-1]
            dst = os.path.join("/tmp", "tmp_buffer_" + name)
            
        OutTile = gdal.Warp(dst,
                            src, 
                            cutlineDSName=shape,
                            cropToCutline=True,
                            dstNodata = dstNodata)
        OutTile = None
        return dst
    
    def onChangeLayer(self, value):
        
        # Already has object
        if(value in self.selected.keys()):
            self.selectedName = value
        else:

            layer = [ layer for layer in self.layers if layer.name() == self.dlg.layerCombo.currentText() ]

            if(len(layer) == 0): print("Info: not in Layers")
            else:
                layer = layer[0].layer()
    
                self.selected[self.dlg.layerCombo.currentText()] = dict()
                self.selected[self.dlg.layerCombo.currentText()]['path'] = layer.dataProvider().dataSourceUri()
                self.selected[self.dlg.layerCombo.currentText()]['type'] = self.type['layer']

                self.selectedName = self.dlg.layerCombo.currentText()

    def onChangeVector(self, value):
        if(value in self.selected.keys()):
            self.selectedNameVector = value
        else:
            vector = [ layer for layer in self.layers if layer.name() == self.dlg.vectorCombo.currentText() ]

            if(len(vector) == 0): print("Info: not in Layers")
            else:
                vector = vector[0].layer()
    
                self.selected[self.dlg.vectorCombo.currentText()] = dict()
                self.selected[self.dlg.vectorCombo.currentText()]['path'] = vector.dataProvider().dataSourceUri()
                self.selected[self.dlg.vectorCombo.currentText()]['type'] = self.type['layer']

                self.selectedNameVector = self.dlg.vectorCombo.currentText()

    def chosenTreeItem(self, item, index):
        
        _item = item.clone()
        itemName = _item.text(index)

        # if last child level
        if(len(_item.takeChildren()) == 0):

            # create a tmp file and save image
            dst = self.saveLayer(os.path.join("/tmp", itemName), self.methodItem[itemName])

            layer = QgsRasterLayer(dst, itemName)
            self.plotCanvas(layer)

    def options(self, imagesArr=[]):

        if(len(imagesArr) == 0): return
        else:

            # Rotate 90
            if self.dlg.rotate90.isChecked():

                if not('rotate' in self.methods.keys()): self.methods["rotate"] = dict() # If not exists create 
                self.methods["rotate"]["rotate90"] = dict()

                for image in imagesArr:

                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_ROTATE90.tif" # Example: /tmp/tmp_point_0_BUFFER_LC08_L1TP_220068_20210101_CROP_CROP_ROTATE90.tif
                    _outName = os.path.splitext(os.path.split(_out)[1])[0] # Example: tmp_point_0_BUFFER_LC08_L1TP_220068_20210101_CROP_CROP_ROTATE90
                    _img = methods_augmentate.rotate(dataset["bandArr"], 90)

                    # self.methods["rotate"]["rotate90"] = dict()
                    self.methods["rotate"]["rotate90"][_outName] = dict()
                    self.methods["rotate"]["rotate90"][_outName]["image"] = _img
                    self.methods["rotate"]["rotate90"][_outName]["name"]  = _outName
                    self.methods["rotate"]["rotate90"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Rotate180
            if self.dlg.rotate180.isChecked():

                if not('rotate' in self.methods.keys()): self.methods["rotate"] = dict() # If not exists create 
                self.methods["rotate"]["rotate180"] = dict()

                for image in imagesArr:

                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_ROTATE180.tif" 
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.rotate(dataset["bandArr"], 180)

                    # self.methods["rotate"]["rotate90"] = dict()
                    self.methods["rotate"]["rotate180"][_outName] = dict()
                    self.methods["rotate"]["rotate180"][_outName]["image"] = _img
                    self.methods["rotate"]["rotate180"][_outName]["name"]  = _outName
                    self.methods["rotate"]["rotate180"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img
            
            # Flip Hor
            if self.dlg.flipHor.isChecked():
                
                if not('flip' in self.methods.keys()): self.methods["flip"] = dict() # If not exists create 
                self.methods["flip"]["horizontal"] = dict()

                for image in imagesArr:

                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_FLIP_HOR.tif" 
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.flip(dataset["bandArr"], 'horizontal')

                    # self.methods["rotate"]["rotate90"] = dict()
                    self.methods["flip"]["horizontal"][_outName] = dict()
                    self.methods["flip"]["horizontal"][_outName]["image"] = _img
                    self.methods["flip"]["horizontal"][_outName]["name"]  = _outName
                    self.methods["flip"]["horizontal"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Flip Ver
            if self.dlg.flipVer.isChecked():

                if not('flip' in self.methods.keys()): self.methods["flip"] = dict() # If not exists create 
                self.methods["flip"]["vertical"] = dict()

                for image in imagesArr:

                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)
                        
                    _out = root + "_FLIP_VER.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.flip(dataset["bandArr"], "vertical")

                    self.methods["flip"]["vertical"][_outName] = dict()
                    self.methods["flip"]["vertical"][_outName]["image"] = _img
                    self.methods["flip"]["vertical"][_outName]["name"]  = _outName
                    self.methods["flip"]["vertical"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Rescale
            if self.dlg.rescale.isChecked():

                if not('reshape' in self.methods.keys()): self.methods["reshape"] = dict() # If not exists create 
                self.methods["reshape"]["rescale"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)
                        
                    _out = root + "_RESCALE.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.rescale(dataset["bandArr"], 0.5)
                    
                    self.methods["reshape"]["rescale"][_outName] = dict()
                    self.methods["reshape"]["rescale"][_outName]["image"] = _img
                    self.methods["reshape"]["rescale"][_outName]["name"]  = _outName
                    self.methods["reshape"]["rescale"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Crop
            if self.dlg.crop.isChecked():
                
                if not('reshape' in self.methods.keys()): self.methods["reshape"] = dict() # If not exists create 
                self.methods["reshape"]["crop"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_CROP.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.crop(dataset["bandArr"], 100, 100, 200, 200)

                    self.methods["reshape"]["crop"][_outName] = dict()
                    self.methods["reshape"]["crop"][_outName]["image"] = _img
                    self.methods["reshape"]["crop"][_outName]["name"]  = _outName
                    self.methods["reshape"]["crop"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Truncate
            if self.dlg.truncate.isChecked():

                if not('reshape' in self.methods.keys()): self.methods["reshape"] = dict() # If not exists create 
                self.methods["reshape"]["truncate"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_TRUNC.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.trunc(dataset["bandArr"], 100, 200)

                    self.methods["reshape"]["truncate"][_outName] = dict()
                    self.methods["reshape"]["truncate"][_outName]["image"] = _img
                    self.methods["reshape"]["truncate"][_outName]["name"]  = _outName
                    self.methods["reshape"]["truncate"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Trim
            if self.dlg.trim.isChecked():

                if not('reshape' in self.methods.keys()): self.methods["reshape"] = dict() # If not exists create 
                self.methods["reshape"]["trim"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_TRIM.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.trim(dataset["bandArr"], 200, 200, 20, 20)
                    self.methods["reshape"]["trim"][_outName] = dict()
                    self.methods["reshape"]["trim"][_outName]["image"] = _img
                    self.methods["reshape"]["trim"][_outName]["name"]  = _outName
                    self.methods["reshape"]["trim"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Binary
            if self.dlg.binary.isChecked():

                if not('color' in self.methods.keys()): self.methods["color"] = dict() # If not exists create 
                self.methods["color"]["binary"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_BINARY.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.binary(dataset["bandArr"], bw=False, threshold=50, inv=True)

                    self.methods["color"]["binary"][_outName] = dict()
                    self.methods["color"]["binary"][_outName]["image"] = _img
                    self.methods["color"]["binary"][_outName]["name"]  = _outName
                    self.methods["color"]["binary"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Cloud
            if self.dlg.checkBox_15.isChecked():

                if not('remote_sensing' in self.methods.keys()): self.methods["remote_sensing"] = dict() # If not exists create 
                self.methods["remote_sensing"]["cloud"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_CLOUD.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.cloud(dataset["bandArr"])

                    self.methods["remote_sensing"]["cloud"][_outName] = dict()
                    self.methods["remote_sensing"]["cloud"][_outName]["image"] = _img
                    self.methods["remote_sensing"]["cloud"][_outName]["name"]  = _outName
                    self.methods["remote_sensing"]["cloud"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Degradation
            if self.dlg.checkBox_17.isChecked():

                if not('remote_sensing' in self.methods.keys()): self.methods["remote_sensing"] = dict() # If not exists create 
                self.methods["remote_sensing"]["degradation"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)
                    
                    _out = root + "_DEGRADATION.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.gdalDecreaseResolution(dataset["dataset"], image)

                    self.methods["remote_sensing"]["degradation"][_outName] = dict()
                    self.methods["remote_sensing"]["degradation"][_outName]["image"] = _img
                    self.methods["remote_sensing"]["degradation"][_outName]["name"]  = _outName
                    self.methods["remote_sensing"]["degradation"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Haze
            if self.dlg.checkBox_16.isChecked():

                if not('remote_sensing' in self.methods.keys()): self.methods["remote_sensing"] = dict() # If not exists create 
                self.methods["remote_sensing"]["haze"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_BLUR.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.blur(dataset["bandArr"], sigma=2)

                    self.methods["remote_sensing"]["haze"][_outName] = dict()
                    self.methods["remote_sensing"]["haze"][_outName]["image"] = _img
                    self.methods["remote_sensing"]["haze"][_outName]["name"]  = _outName
                    self.methods["remote_sensing"]["haze"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img

            # Edgy
            if self.dlg.checkBox_18.isChecked():

                if not('remote_sensing' in self.methods.keys()): self.methods["remote_sensing"] = dict() 
                self.methods["remote_sensing"]["sharpen_edges"] = dict()

                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)

                    _out = root + "_SHARPENEDGES.tif"
                    _outName = os.path.splitext(os.path.split(_out)[1])[0]
                    _img = methods_augmentate.edgy(dataset["bandArr"])

                    self.methods["remote_sensing"]["sharpen_edges"][_outName] = dict()
                    self.methods["remote_sensing"]["sharpen_edges"][_outName]["image"] = _img
                    self.methods["remote_sensing"]["sharpen_edges"][_outName]["name"]  = _outName
                    self.methods["remote_sensing"]["sharpen_edges"][_outName]["path"]  = _out

                    self.methodItem[_outName] = _img
            
            # Augmentate
            if self.dlg.augmentate.isChecked():

                if not('augmentate' in self.methods.keys()): self.methods["augmentate"] = dict() 
                
                for image in imagesArr:
                    
                    dataset = self.readLayer(src=image)
                    root, ext = os.path.splitext(image)
                    _outName = os.path.splitext(os.path.split(image)[1])[0]

                    images, labelImage, q = methods_augmentate.augmentate(dataset["bandArr"], name=_outName, chunks=50)

                    # Merge to dict used to save tmp file {key: image array}
                    self.methodItem.update(labelImage)

                    if(len(self.methods['augmentate'].keys()) == 0):
                        self.methods["augmentate"] = images
                    else:
                        self.methods["augmentate"].update(images)

    def plotCanvas(self, layer):

        QgsProject.instance().addMapLayer(layer, False)

        self.dlg.canvas.clearCache()
        self.dlg.canvas.refresh()

        self.dlg.canvas.setExtent(layer.extent())
        self.dlg.canvas.setLayers([layer])
        self.dlg.canvas.refresh()

    def treeView(self):
        
        self.dlg.treeWidget.clear()

        for key in self.methods.keys():
            self.child = QTreeWidgetItem([key])

            for key2 in self.methods[key].keys():
                child2 = QTreeWidgetItem([key2])

                for key3 in self.methods[key][key2].keys():
                    child3 = QTreeWidgetItem([self.methods[key][key2][key3]['name']])
                    child2.addChild(child3)

                self.child.addChild(child2)
            
            self.dlg.treeWidget.addTopLevelItem(self.child)

    def main(self):

        # reset variable
        self.vectorsPath = []
        self.imagesArray = []
        self.vectorsBufferPath = []

        # self.dlg.canvas.scene().clear()

        # Get selected layer and vector index
        self.selectedLayerIndex  = self.dlg.layerCombo.currentIndex()
        self.selectedVectorIndex = self.dlg.vectorCombo.currentIndex()

        # Get output path, por padrao /tmp
        self.outputDir  = "/tmp" #self.selectedLayerPath if self.selectedLayerPath != None else "/tmp"

        # Required fields

        # Required Layer
        if(self.selectedLayerIndex == -1):
            self.iface.messageBar().pushMessage("Error", "Required select layer", level=Qgis.Critical)
            return

        # Required Vector
        elif(self.selectedVectorIndex == -1):
            
            # If not vector do with all image if is not too big
            self.iface.messageBar().pushMessage("Error", "Vector not provided, trying with the whole image", level=Qgis.Info, duration=3)

            # self.iface.messageBar().pushMessage("Error", "Required select vector", level=Qgis.Critical)
            # return

        # Get selected layer and vector

        # If not chosen file from button
        if(len(self.layers) == 0): print("Info: layer empty")
        else:
            if(self.selectedName == None):

                # Must be on layers
                layer = [ layer for layer in self.layers if layer.name() == self.dlg.layerCombo.currentText() ][0].layer()

                self.selected[self.dlg.layerCombo.currentText()] = dict()
                self.selected[self.dlg.layerCombo.currentText()]['path'] = layer.dataProvider().dataSourceUri()
                self.selected[self.dlg.layerCombo.currentText()]['type'] = self.type['layer']

                self.selectedName = self.dlg.layerCombo.currentText()


            if(self.selectedNameVector == None):
                vector = [ layer for layer in self.layers if layer.name() == self.dlg.vectorCombo.currentText() ]
                
                if(len(vector) > 0):
                    vector = vector[0].layer()

                    self.selected[self.dlg.vectorCombo.currentText()] = dict()
                    self.selected[self.dlg.vectorCombo.currentText()]['path'] = vector.dataProvider().dataSourceUri()
                    self.selected[self.dlg.vectorCombo.currentText()]['type'] = self.type['vector']
                    
                    self.selectedNameVector = self.dlg.vectorCombo.currentText()


        # print(self.selectedName)
        # print(self.selectedNameVector)
        # print(self.selected[self.selectedNameVector]['path'])

        # Clip by vector
        if(self.selectedNameVector and self.selectedName):

            self.splitPoint() # feed self.vectorsPath array
            print(self.vectorsPath)

            # Save Buffer array 
            for vector in self.vectorsPath:
                dst = vector.replace(".shp", "_BUFFER.shp")
                buffer = self.getBufferPoint(vector, dst)
                self.vectorsBufferPath.append(buffer)

            # Clip image by buffer vectors array
            for buffer in self.vectorsBufferPath:
                dst = buffer.replace(".shp", "_" + self.selectedName + "_CROP.tif")
                image = self.cropLayerByShape(self.selected[self.selectedName]['path'], buffer, dst)
                self.imagesArray.append(image)
        

        # print(self.vectorsBufferPath)
        print(self.imagesArray)

        # Get array and info from selected layer
        # responseRL = self.readLayer()
        responseRL = "ok"
        if(responseRL == "err"): 
            self.iface.messageBar().pushMessage("Error", "Image too large, please provide de vector file", level=Qgis.Critical)
            return
        else:
            # check chosen methods
            self.options(imagesArr=self.imagesArray)

            # Create Tree View
            self.treeView()

            # message success
            self.iface.messageBar().pushMessage( "Success!", level=Qgis.Success, duration=3)
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:

            # clear /tmp 
            for ext in ("*.tif", "*.dbf", "*.shp", "*.prj", "*.shx", "*.xml"):
                for f in glob.glob("/tmp/" + ext):
                    os.remove(f)

            self.first_start = False
            self.dlg = DataAugmentationDialog()


            # On click button select output file
            self.dlg.layerButton.clicked.connect(self.selectLayerFile)
            self.dlg.vectorButton.clicked.connect(self.selectVectorFile)
            
            # On click tree view
            self.dlg.treeWidget.itemDoubleClicked.connect(self.chosenTreeItem)

            # On click run
            self.dlg.run.clicked.connect(self.main)

            # Change combobox
            self.dlg.layerCombo.currentTextChanged.connect(self.onChangeLayer)
            self.dlg.vectorCombo.currentTextChanged.connect(self.onChangeVector)
        
        
        tool = QgsMapToolPan(self.dlg.canvas)
        self.dlg.canvas.setMapTool(tool)

        # Get all active layers on the screen
        self.layers = QgsProject.instance().layerTreeRoot().children()

        # Clear the contents of the layerCombo from previous runs
        self.dlg.layerCombo.clear()
        self.dlg.vectorCombo.clear()

        # Populate the layerCombo with names of all the loaded layers
        # Check if there is layers
        if not(len(self.layers) == 0): 
            self.dlg.layerCombo.addItems([layer.name() for layer in self.layers if not(os.path.splitext(layer.layer().dataProvider().dataSourceUri().lower())[1] in self.sf) ])
            self.dlg.vectorCombo.addItems([layer.name() for layer in self.layers if(os.path.splitext(layer.layer().dataProvider().dataSourceUri().lower())[1] in self.sf) ])

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        
        if result:
            pass
